name: "Deploy to AWS"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install 

      - name: "Install PM2"
        run: npm install -g pm2

      - name: "Run the tests"
        run: npm test

      - name: "Start or Restart App with PM2"
        run: |
          pm2 describe server || pm2 start src/index.js --name server
          pm2 restart server
