name: "Deploy to AWS"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Ensure PM2 is installed"
        run: |
          which pm2 || npm install -g pm2

      - name: "Run tests"
        run: npm test

      - name: "Start or restart server with PM2"
        run: |
          pm2 describe server || pm2 start src/index.js --name server
          pm2 restart server
